function P = get_parameter_table(CLVALS)

P = struct( ...
 'Area',              {{CLVALS.area_val,              [0 1.5*mean(CLVALS.area)], ...
                        {'Area: ',' cm^2';'Average: ',' cm^2'}, 'Area (cm^2)'}}, ...
 'Ratio of Areas',    {{CLVALS.CC_val,                [], ...
                        {'Area Ratio: ',' ';'Average: ',' '}, 'CSF Coupling'}}, ...
 'Total Flow',        {{CLVALS.flowTA, [0 0.8*max(CLVALS.flowTA(:))], ...
                        {'Flow: ',' mL/s';'Average: ',' mL/s'}, 'Flow (mL/s)'}}, ...
 'Maximum Velocity ', {{CLVALS.maxVel,            [], ...
                        {'Max Velocity: ',' cm/s';'Average: ',' cm/s'}, 'Max Velocity (cm/s)'}}, ...
 'Mean Velocity',     {{CLVALS.velMean,           [], ...
                        {'Mean Velocity: ',' cm/s';'Average: ',' cm/s'}, 'Mean Velocity (cm/s)'}}, ...
 'Flow Consistency',  {{CLVALS.StdvFromMean,          [0 4], ...
                        {'Flow Consistency: ',' ';'Stdv from Mean: ',' '}, 'Flow Consistency'}}, ...
 'Resistance Index',  {{CLVALS.RI,                [-0.5 1], ...
                        {'Resistance Index: ',' ';'Average: ',' '}, 'Resistance Index'}}, ...
 'CSF Coupling: ',    {{CLVALS.CC,                [-1 1], ...
                        {'CSF Coupling: ',' ';'Average: ',' '}, 'CSF Coupling'}}, ...
 'Pulsatility Index', {{CLVALS.PI,                [0 2], ...
                        {'Pulsatility Index: ',' ';'Average: ',' '}, 'Pulsatility Index'}} );

end